### PR TITLE
Fix building source distribution

### PR DESCRIPTION
**Pull request by bdraco**
test build https://github.com/bdraco/cChardet/actions/runs/4235224989/jobs/7358582208

### CODE REVIEW

**Comment by wbarnha** [comment]
Thanks again for the work!

**Comment by bdraco** [comment]
```
% pip3 wheel faust-cchardet-2.1.18.tar.gz     
Processing ./faust-cchardet-2.1.18.tar.gz
  File was already downloaded /Users/bdraco/faust-cchardet-2.1.18.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: faust-cchardet
  Building wheel for faust-cchardet (pyproject.toml) ... done
  Created wheel for faust-cchardet: filename=faust_cchardet-2.1.18-cp310-cp310-macosx_13_0_arm64.whl size=124741 sha256=4b0bd75837d6a648482b81143feb00456c25472136b47cae36d67c825cb910c2
  Stored in directory: /Users/bdraco/Library/Caches/pip/wheels/fc/f2/51/265cd375b81fe95c5efe4d8ed699af709795b66974f04666ef
Successfully built faust-cchardet

[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python3.10 -m pip install --upgrade pip
```

Looks good now.

Hopefully it behaves exactly the same way on the GH run

**Review by wbarnha — APPROVED** [review]
Shame on me for not seeing this change sooner. I was wondering what the motivation for the initial change was, but I didn't think it'd break source builds.

**Comment by bdraco** [comment]
Thanks @wbarnha 

Tested the following on macos and linux and 👍 
`pip3 wheel --no-binary faust-cchardet -vvvv faust-cchardet==2.1.18`

**Pull request merged**
